### ISSUE TITLE
mastcasjobs 0.2 breaks code written with 0.1 version

### ISSUE THREAD

**Issue by prinewgirl-zz** [rlwastro/mastcasjobs#1]
Hi,
Our research group wrote a code with mascasjobs 0.1 and it brokes when we run it with the latest version (i got a lot of errors from astropy).
I've tested it and the code only works when i revert the commits of mastcasjobs til 3c27f7ff7aff933694058b5204abd72527115244.

**Comment by rlwastro** [comment]
Thanks for the feedback -- can you give me some more info?  Ideal would be a piece of code that works with version 0.1 but fails with the current version.

**Comment by rlwastro** [comment]
Hi - maybe what I need to reproduce this is information about the Python version and astropy version (astropy.__version__) you are using.  Even a snippet of the code that is failing or the traceback would be helpful.

**Comment by prinewgirl-zz** [comment]
I'm sending to you my currently packages (python 2.7) and the code. Hope it helps!
mastcastjobs did not work with python3, so I used python2.7 instead.
[pypack.txt](https://github.com/rlwastro/mastcasjobs/files/3726758/pypack.txt)
[PS1zxcorr.zip](https://github.com/rlwastro/mastcasjobs/files/3726760/PS1zxcorr.zip)

**Comment by rlwastro** [comment]
Hmm, this package has a lot of dependencies to use for testing.  I so far have not been able to install healpy using the Python 2 version of anaconda (it wants to downgrade numpy).

Can you try this? Download the zip file below:
[rlwtest.zip](https://github.com/rlwastro/mastcasjobs/files/3731760/rlwtest.zip)
It has a super-simple Casjobs query along with the current version of mastcasjobs.py. Try running the test.py script from Python (simply using python test.py).  For me that works for both Python 2 and Python 3.  Let me know if you see an error and what the traceback is.

**Comment by prinewgirl-zz** [comment]
I got the following output:
![image](https://user-images.githubusercontent.com/6698424/67118249-df0ea200-f1ba-11e9-80d6-00a923f177f8.png)

**Comment by rlwastro** [comment]
To connect to Casjobs without specifying your user information in the call, you need to specify one of these environment variables:

CASJOBS_WSID = your WSID (an integer with ~9 digits)
CASJOBS_USERID = your Casjobs username

You also need to specify

CASJOBS_PW = your casjobs password

The ability to specify your username rather than the WSID is a new feature added in the more recent version of mastcasjobs.  But it should still work with a WSID, which is what was required before.

I assume from your code (which always omits the user and password parameters) that you must have had the CASJOBS_WSID and CASJOBS_PW environment variables defined.  Can you check that and then test this again?  Thanks.

**Comment by rlwastro** [comment]
I assume this problem is resolved since there were no followup comments.
