### ISSUE TITLE
Exception: GetJobStatus failed with status: 500

### ISSUE THREAD

**Issue by entaylor** [rlwastro/mastcasjobs#12]
I am trying to script the running of a number of casjob queries of the ps1 database.

I am consistently running into the following Exception:
> Exception: GetJobStatus failed with status: 500
> System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
>    at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
> 

The line of code where this exception is thrown is:
        status = mast.monitor( jobid )

This hasn't yet happened on the first job, but doesn't always happen on, say, the second one.  It is always true that subsequent jobs have different task_names.  It takes some significant time between when the job is submitted and the exception gets thrown; i don't know precisely, but more than 1 hour.  It's not like the exception gets thrown when the job starts; the jobs are still sitting in the queue.

Here is the essential part of my script, if only to show i'm not doing anything particularly clever or fancy to get myself into trouble:
        mast = MastCasJobs( username, password,
                            context='PanSTARRS_DR2' )
        # construct query by filling in essential values to boilerplate _query
        query = _query.format(
            projectionID=projectionID, task_name=task_name,
            dec_min=dec_min, dec_max=dec_max)

        mast.drop_table_if_exists( task_name )

        jobid = mast.submit( query, task_name=task_name, estimate=10 )

        status = mast.monitor( jobid )
        # failure here, but only after some (long) time

I had used these scripts and code quite successfully about a year ago.  I don't think that i have changed anything in my script that might be producing this apparent clash of commands.  It's possible something changed on the ps1 server side, maybe?  But i don't see anyway to influence the situation within mastcasjobs.

I'm not sure whether there is a need for some extra settings or error handling within mastcasjobs, but ... well, very grateful for whatever advice or guidance you can offer!

**Comment by rlwastro** [comment]
If you login to your Casjobs web account, you can look at the failure messages for the jobs.  The mastcasjobs module doesn't do a great job of capturing that info and reporting the problem (that is certainly an area for improvement).  I checked your account and found that at least some of the failures were due to running out of space in your MyDB.  You had a very small quota (probably because your account was created back in 2005!).  I increased it by a factor of 10.

Try running more jobs to see if that fixes the problem.  It is possible there is some additional underlying issue, so definitely let us know if you encounter more issues!

**Comment by rlwastro** [comment]
@entaylor I don't see any signs of new failures for your jobs, so I'm going to assume increasing your MyDB quota fixed the problem.  I will close this ticket, but please let us know if you encounter more problems.
